export const MockData = [
  {
    id: 1,
    name: 'kim****',
    writtenAt: '2024-07-01',
    rating: 5,
    content: '듣던대로 정말 친절하시고 물건도 잘 옮겨주셨어요~~',
  },
  {
    id: 2,
    name: 'lee****',
    writtenAt: '2024-07-02',
    rating: 4,
    content: '기사님 덕분에 안전하고 신속한 이사를 했습니다! 감사합니다~',
  },
  {
    id: 3,
    name: 'park****',
    writtenAt: '2024-07-03',
    rating: 5,
    content: '추천받아서 견적을 받았는데, 덕분에 문제없이 이사했어요!',
  },
  {
    id: 4,
    name: 'choi****',
    writtenAt: '2024-07-04',
    rating: 3,
    content: '친절하시지만 조금 더 빠르면 좋겠어요!',
  },
  {
    id: 5,
    name: 'jung****',
    writtenAt: '2024-07-05',
    rating: 5,
    content: '리뷰 내용대로 꼼꼼하네요! 감사합니다 :)',
  },
  {
    id: 6,
    name: 'kang****',
    writtenAt: '2024-07-06',
    rating: 4,
    content: '포장이 꼼꼼해서 만족스러웠어요. 다음에도 이용할게요!',
  },
  {
    id: 7,
    name: 'yoon****',
    writtenAt: '2024-07-07',
    rating: 5,
    content: '이사업체 여러 곳 비교하다가 선택했는데 정말 만족합니다!',
  },
  {
    id: 8,
    name: 'han****',
    writtenAt: '2024-07-08',
    rating: 4,
    content: '기사님 너무 친절하시고 가구 배치도 도와주셨어요.',
  },
  {
    id: 9,
    name: 'shin****',
    writtenAt: '2024-07-09',
    rating: 3,
    content: '생각보다 시간이 좀 걸렸지만, 그래도 만족합니다.',
  },
  {
    id: 10,
    name: 'seo****',
    writtenAt: '2024-07-10',
    rating: 5,
    content: '이사 일정이 급했는데 신속하게 도와주셔서 감사합니다!',
  },
  {
    id: 11,
    name: 'hwang****',
    writtenAt: '2024-07-11',
    rating: 4,
    content: '가격 대비 서비스가 훌륭합니다. 추천해요!',
  },
  {
    id: 12,
    name: 'ahn****',
    writtenAt: '2024-07-12',
    rating: 5,
    content: '고층 이사라 걱정했는데 너무 안전하게 작업해주셨어요!',
  },
  {
    id: 13,
    name: 'jo****',
    writtenAt: '2024-07-13',
    rating: 4,
    content: '짐이 많았는데도 깔끔하게 정리해주셨네요. 감사합니다!',
  },
  {
    id: 14,
    name: 'ryu****',
    writtenAt: '2024-07-14',
    rating: 3,
    content: '친절하지만 일정이 조금 늦어져서 아쉬웠어요.',
  },
  {
    id: 15,
    name: 'moon****',
    writtenAt: '2024-07-15',
    rating: 5,
    content: '원룸 이사였는데 빠르고 정확하게 처리해주셨습니다!',
  },
];
